[[vamana_dynamic_build]]
__schema__ = 'benchmark_vamana_dynamic_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
dynamic_optimization = 'minimal'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'

    [vamana_dynamic_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'uncompressed'

        [vamana_dynamic_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_uncompressed'
        __version__ = 'v0.0.0'
        data_type = 'float16'

    [vamana_dynamic_build.dynamic_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __schema__ = 'benchmark_dynamic_schedule'
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    rng_seed = 12648430
    total_iterations = 20

        [vamana_dynamic_build.schedule.search_parameters]
        __schema__ = 'benchmark_search_parameters'
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.90000000000000002 ]

[[vamana_dynamic_build]]
__schema__ = 'benchmark_vamana_dynamic_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
dynamic_optimization = 'minimal'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'

    [vamana_dynamic_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 8
        residual = 0
        strategy = 'sequential'

    [vamana_dynamic_build.dynamic_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __schema__ = 'benchmark_dynamic_schedule'
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    rng_seed = 12648430
    total_iterations = 20

        [vamana_dynamic_build.schedule.search_parameters]
        __schema__ = 'benchmark_search_parameters'
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.90000000000000002 ]

[[vamana_dynamic_build]]
__schema__ = 'benchmark_vamana_dynamic_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
dynamic_optimization = 'minimal'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'

    [vamana_dynamic_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = 'sequential'

    [vamana_dynamic_build.dynamic_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __schema__ = 'benchmark_dynamic_schedule'
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    rng_seed = 12648430
    total_iterations = 20

        [vamana_dynamic_build.schedule.search_parameters]
        __schema__ = 'benchmark_search_parameters'
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.90000000000000002 ]

[[vamana_dynamic_build]]
__schema__ = 'benchmark_vamana_dynamic_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
dynamic_optimization = 'minimal'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'

    [vamana_dynamic_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 8
        residual = 8
        strategy = 'sequential'

    [vamana_dynamic_build.dynamic_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __schema__ = 'benchmark_dynamic_schedule'
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    rng_seed = 12648430
    total_iterations = 20

        [vamana_dynamic_build.schedule.search_parameters]
        __schema__ = 'benchmark_search_parameters'
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.90000000000000002 ]

[[vamana_dynamic_build]]
__schema__ = 'benchmark_vamana_dynamic_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
dynamic_optimization = 'minimal'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'

    [vamana_dynamic_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_dynamic_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_dynamic_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = 'turbo<16x8>'

    [vamana_dynamic_build.dynamic_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = false
    window_size = 200

    [vamana_dynamic_build.schedule]
    __schema__ = 'benchmark_dynamic_schedule'
    __version__ = 'v0.0.1'
    bucket_divisor = 32
    cycles_before_cleanup = 5
    initial_fraction = 0.75
    modify_fraction = 0.01
    rng_seed = 12648430
    total_iterations = 20

        [vamana_dynamic_build.schedule.search_parameters]
        __schema__ = 'benchmark_search_parameters'
        __version__ = 'v0.0.0'
        num_neighbors = 10
        target_recalls = [ 0.90000000000000002 ]
