[[vamana_static_build]]
__schema__ = 'benchmark_vamana_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'uncompressed'

        [vamana_static_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_uncompressed'
        __version__ = 'v0.0.0'
        data_type = 'float16'

    [vamana_static_build.search_parameters]
    __schema__ = 'benchmark_search_parameters'
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.80000000000000004, 0.84999999999999998, 0.90000000000000002 ]

[[vamana_static_build]]
__schema__ = 'benchmark_vamana_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 8
        residual = 0
        strategy = 'sequential'

    [vamana_static_build.search_parameters]
    __schema__ = 'benchmark_search_parameters'
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.80000000000000004, 0.84999999999999998, 0.90000000000000002 ]

[[vamana_static_build]]
__schema__ = 'benchmark_vamana_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 8
        residual = 0
        strategy = 'turbo<16x4>'

    [vamana_static_build.search_parameters]
    __schema__ = 'benchmark_search_parameters'
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.80000000000000004, 0.84999999999999998, 0.90000000000000002 ]

[[vamana_static_build]]
__schema__ = 'benchmark_vamana_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = 'sequential'

    [vamana_static_build.search_parameters]
    __schema__ = 'benchmark_search_parameters'
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.80000000000000004, 0.84999999999999998, 0.90000000000000002 ]

[[vamana_static_build]]
__schema__ = 'benchmark_vamana_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 4
        residual = 8
        strategy = 'turbo<16x8>'

    [vamana_static_build.search_parameters]
    __schema__ = 'benchmark_search_parameters'
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.80000000000000004, 0.84999999999999998, 0.90000000000000002 ]

[[vamana_static_build]]
__schema__ = 'benchmark_vamana_build_job'
__version__ = 'v0.0.3'
data = 'dpr/dpr_1m_f16.fvecs'
data_type = 'float16'
description = 'dpr-1m'
distance = 'MIP'
groundtruth = 'dpr/dpr_1m_groundtruth_ip_10k.ivecs'
ndims = 768
num_threads = 72
queries = 'dpr/dpr_queries_10k_f32.fvecs'
queries_in_training_set = 5000
query_type = 'float32'
search_window_sizes = []

    [vamana_static_build.build_parameters]
    __schema__ = 'vamana_build_parameters'
    __version__ = 'v0.0.1'
    alpha = 0.94999999999999996
    graph_max_degree = 128
    max_candidate_pool_size = 750
    name = 'vamana build parameters'
    prune_to = 124
    use_full_search_history = true
    window_size = 200

    [vamana_static_build.dataset]
    __schema__ = 'benchmark_dataset_abstract'
    __version__ = 'v0.0.0'
    kind = 'lvq'

        [vamana_static_build.dataset.dataset]
        __schema__ = 'benchmark_dataset_lvq'
        __version__ = 'v0.0.0'
        primary = 8
        residual = 8
        strategy = 'sequential'

    [vamana_static_build.search_parameters]
    __schema__ = 'benchmark_search_parameters'
    __version__ = 'v0.0.0'
    num_neighbors = 10
    target_recalls = [ 0.80000000000000004, 0.84999999999999998, 0.90000000000000002 ]
