# Copyright (C) 2025 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you ("License"). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written
# permission.
#
# This software and the related documents are provided as is, with no
# express or implied warranties, other than those that are expressly stated
# in the License.

name: Linux Build and Test
run-name: ${{ github.event.inputs.run_name || github.event.pull_request.title }}

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  asan-test:
    name: clang-18 fsanitize=address
    runs-on: [self-hosted, Linux, ubuntu-22.04]
    env:
      CXX: clang++-18
      CC: clang-18

    steps:
      - name: "Cleanup build folder"
        run: |
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure build
        working-directory: ${{ runner.temp }}
        env:
          TEMP_WORKSPACE: ${{ runner.temp }}
        run: |
          cmake -B${TEMP_WORKSPACE}/build -S${GITHUB_WORKSPACE} \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" \
                -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" \
                -DSVS_BUILD_TESTS=YES \
                -DSVS_BUILD_BINARIES=NO \
                -DSVS_BUILD_EXAMPLES=NO

      - name: Build tests
        working-directory: ${{ runner.temp }}/build
        run: make tests -j

      - name: Run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
          ASAN_OPTIONS: detect_leaks=0
        working-directory: ${{ runner.temp }}/build/tests
        run: ./tests
